 const movies = [
  {
    id: 1,
    name: "Dangal",
    description: "The true story of Mahavir Singh Phogat, a former wrestler who trains his daughters to become world-class wrestlers against all societal odds.",
    duration: "2h 41m",
    releaseDate: "2016-12-23",
    cast: "Aamir Khan,Sakshi Tanwar,Fatima Sana Shaikh",
    director: "Nitesh Tiwari",
    producer: "Aamir Khan, Kiran Rao",
    rating: 8.4,
    officialUrl: "https://www.youtube.com/watch?v=x_7YlGv9u1g",
    image: "https://upload.wikimedia.org/wikipedia/en/9/99/Dangal_Poster.jpg"
  },
  {
    id: 2,
    name: "Baahubali 2: The Conclusion",
    description: "Shiva, the son of Bahubali, learns about his heritage and begins to look for answers while facing a powerful tyrant.",
    duration: "2h 45m",
    releaseDate: "2017-04-28",
    cast: "Prabhas,Anushka Shetty,Rana Daggubati",
    director: "S.S. Rajamouli",
    producer: "Shobu Yarlagadda, Prasad Devineni",
    rating: 8.2,
    officialUrl: "https://www.youtube.com/watch?v=qD-6d8Wo3do",
    image: "https://upload.wikimedia.org/wikipedia/en/9/93/Baahubali_2_The_Conclusion_poster.jpg"
  },
  {
    id: 3,
    name: "RRR",
    description: "A fearless revolutionary and an officer in the British army, who are best friends, join forces to fight for freedom.",
    duration: "2h 57m",
    releaseDate: "2022-03-25",
    cast: "N. T. Rama Rao Jr.,Ram Charan,Alia Bhatt",
    director: "S.S. Rajamouli",
    producer: "D. V. V. Danayya",
    rating: 8.1,
    officialUrl: "https://www.youtube.com/watch?v=GY4BgdUSpbE",
    image: "https://upload.wikimedia.org/wikipedia/en/d/d7/RRR_Poster.jpg"
  },
  {
    id: 4,
    name: "K.G.F: Chapter 2",
    description: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes, but he must face even deadlier threats to maintain his empire.",
    duration: "2h 52m",
    releaseDate: "2022-04-14",
    cast: "Yash,Sanjay Dutt,Raveena Tandon",
    director: "Prashanth Neel",
    producer: "Vijay Kiragandur",
    rating: 8.0,
    officialUrl: "https://www.youtube.com/watch?v=JKa05nyUmuQ",
    image: "https://upload.wikimedia.org/wikipedia/en/d/d0/K.G.F_Chapter_2.jpg"
  },
  {
    id: 5,
    name: "Jawan",
    description: "A man is driven by a personal vendetta to rectify the wrongs in society, while keeping a promise made years ago.",
    duration: "2h 43m",
    releaseDate: "2023-09-07",
    cast: "Shah Rukh Khan,Nayanthara,Vijay Sethupathi",
    director: "Atlee",
    producer: "Gauri Khan",
    rating: 8.0,
    officialUrl: "https://www.youtube.com/watch?v=COv52Qyctws",
    image: "https://upload.wikimedia.org/wikipedia/en/3/39/Jawan_film_poster.jpg"
  },
  {
    id: 6,
    name: "Pushpa: The Rise",
    description: "A laborer rises through the ranks of a red sandalwood smuggling syndicate, making powerful enemies along the way.",
    duration: "2h 34m",
    releaseDate: "2021-12-17",
    cast: "Allu Arjun,Rashmika Mandanna,Fahadh Faasil",
    director: "Sukumar",
    producer: "Naveen Yerneni, Y. Ravi Shankar",
    rating: 7.7,
    officialUrl: "https://www.youtube.com/watch?v=pKctjlxbFDQ",
    image: "https://upload.wikimedia.org/wikipedia/en/7/75/Pushpa_-_The_Rise_%282021_film%29.jpg"
  },
  {
    id: 7,
    name: "3 Idiots",
    description: "Two friends search for their long-lost companion while revisiting their college days and the memories of their friend who inspired them to think differently.",
    duration: "2h 50m",
    releaseDate: "2009-12-25",
    cast: "Aamir Khan,R. Madhavan,Sharman Joshi",
    director: "Rajkumar Hirani",
    producer: "Vidhu Vinod Chopra",
    rating: 8.4,
    officialUrl: "https://www.youtube.com/watch?v=K0eDlFX9GMc",
    image: "https://upload.wikimedia.org/wikipedia/en/d/df/3_idiots_poster.jpg"
  },
  {
    id: 8,
    name: "Lagaan",
    description: "During the British Raj, a group of villagers challenges the British to a game of cricket to avoid paying high taxes.",
    duration: "3h 44m",
    releaseDate: "2001-06-15",
    cast: "Aamir Khan,Gracy Singh,Rachel Shelley",
    director: "Ashutosh Gowariker",
    producer: "Aamir Khan",
    rating: 8.1,
    officialUrl: "https://www.youtube.com/watch?v=Nhi4Azs2nEw",
    image: "https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg"
  },
  {
    id: 9,
    name: "Dilwale Dulhania Le Jayenge",
    description: "A young man and woman fall in love during a vacation in Europe, but the man must win over the woman's conservative family back in India.",
    duration: "3h 0m",
    releaseDate: "1995-10-20",
    cast: "Shah Rukh Khan,Kajol,Amrish Puri",
    director: "Aditya Chopra",
    producer: "Yash Chopra",
    rating: 8.1,
    officialUrl: "https://www.youtube.com/watch?v=cmax1C1p660",
    image: "https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg"
  },
  {
    id: 10,
    name: "Kalki 2898 AD",
    description: "A modern-day avatar of Vishnu, a Hindu god, is believed to have descended to earth to protect the world from evil forces.",
    duration: "2h 55m",
    releaseDate: "2024-06-27",
    cast: "Prabhas,Deepika Padukone,Amitabh Bachchan",
    director: "Nag Ashwin",
    producer: "C. Aswani Dutt",
    rating: 7.9,
    officialUrl: "https://www.youtube.com/watch?v=kQDd1AhGIHk",
    image: "https://upload.wikimedia.org/wikipedia/en/4/4c/Kalki_2898_AD.jpg"
  },
  {
    id: 11,
    name: "Animal",
    description: "A troubled father-son relationship unfolds in a violent underworld filled with power struggles and revenge.",
    duration: "3h 21m",
    releaseDate: "2023-12-01",
    cast: "Ranbir Kapoor,Rashmika Mandanna,Anil Kapoor",
    director: "Sandeep Reddy Vanga",
    producer: "Bhushan Kumar",
    rating: 7.2,
    officialUrl: "https://www.youtube.com/watch?v=Dydmpfo68DA",
    image: "https://upload.wikimedia.org/wikipedia/en/9/90/Animal_%282023_film%29_poster.jpg"
  },
  {
    id: 12,
    name: "Pathaan",
    description: "An exiled RAW agent must stop a dangerous private terrorist organization from launching a deadly attack.",
    duration: "2h 26m",
    releaseDate: "2023-01-25",
    cast: "Shah Rukh Khan,Deepika Padukone,John Abraham",
    director: "Siddharth Anand",
    producer: "Aditya Chopra",
    rating: 7.5,
    officialUrl: "https://www.youtube.com/watch?v=vqu4z34wENw",
    image: "https://upload.wikimedia.org/wikipedia/en/c/c3/Pathaan_film_poster.jpg"
  },
  {
    id: 13,
    name: "Drishyam",
    description: "A man goes to extreme lengths to protect his family after they commit an accidental crime.",
    duration: "2h 43m",
    releaseDate: "2015-07-31",
    cast: "Ajay Devgn,Tabu,Shriya Saran",
    director: "Nishikant Kamat",
    producer: "Kumar Mangat Pathak",
    rating: 8.2,
    officialUrl: "https://www.youtube.com/watch?v=64xJLmcA2K8",
    image: "https://upload.wikimedia.org/wikipedia/en/8/8a/Drishyam_2015_film.jpg"
  },
  {
    id: 14,
    name: "Chennai Express",
    description: "A man traveling to immerse his grandfather’s ashes gets caught in unexpected adventures and love.",
    duration: "2h 21m",
    releaseDate: "2013-08-09",
    cast: "Shah Rukh Khan,Deepika Padukone",
    director: "Rohit Shetty",
    producer: "Gauri Khan",
    rating: 7.0,
    officialUrl: "https://www.youtube.com/watch?v=hZGR5Sj1Bfo",
    image: "https://upload.wikimedia.org/wikipedia/en/1/1b/Chennai_Express.jpg"
  },
  {
    id: 15,
    name: "PK",
    description: "An alien on Earth loses his communication device and questions religious dogmas while searching for it.",
    duration: "2h 33m",
    releaseDate: "2014-12-19",
    cast: "Aamir Khan,Anushka Sharma",
    director: "Rajkumar Hirani",
    producer: "Vidhu Vinod Chopra",
    rating: 8.1,
    officialUrl: "https://www.youtube.com/watch?v=SOXWc32k4zA",
    image: "https://upload.wikimedia.org/wikipedia/en/c/c3/PK_poster.jpg"
  },
  {
    id: 16,
    name: "Bajrangi Bhaijaan",
    description: "A devoted man embarks on a mission to reunite a mute Pakistani girl with her family.",
    duration: "2h 43m",
    releaseDate: "2015-07-17",
    cast: "Salman Khan,Harshaali Malhotra,Kareena Kapoor",
    director: "Kabir Khan",
    producer: "Salman Khan",
    rating: 8.1,
    officialUrl: "https://www.youtube.com/watch?v=4nwAra0mz_Q",
    image: "https://upload.wikimedia.org/wikipedia/en/d/dd/Bajrangi_Bhaijaan_Poster.jpg"
  },
  {
    id: 17,
    name: "Vikram",
    description: "A special agent investigates a series of murders linked to a mysterious masked gang.",
    duration: "2h 54m",
    releaseDate: "2022-06-03",
    cast: "Kamal Haasan,Vijay Sethupathi,Fahadh Faasil",
    director: "Lokesh Kanagaraj",
    producer: "Raaj Kamal Films International",
    rating: 8.3,
    officialUrl: "https://www.youtube.com/watch?v=OKBMCL-frPU",
    image: "https://upload.wikimedia.org/wikipedia/en/9/93/Vikram_2022_poster.jpg"
  },
  {
    id: 18,
    name: "Master",
    description: "An alcoholic professor is sent to a juvenile school where he clashes with a ruthless gangster.",
    duration: "2h 58m",
    releaseDate: "2021-01-13",
    cast: "Vijay,Vijay Sethupathi",
    director: "Lokesh Kanagaraj",
    producer: "Xavier Britto",
    rating: 7.4,
    officialUrl: "https://www.youtube.com/watch?v=UTiXQcrLlv4",
    image: "https://upload.wikimedia.org/wikipedia/en/5/53/Master_2021_poster.jpg"
  },
  {
    id: 19,
    name: "Sultan",
    description: "A wrestler battles personal issues and professional setbacks while trying to reclaim his glory.",
    duration: "2h 50m",
    releaseDate: "2016-07-06",
    cast: "Salman Khan,Anushka Sharma",
    director: "Ali Abbas Zafar",
    producer: "Aditya Chopra",
    rating: 7.0,
    officialUrl: "https://www.youtube.com/watch?v=wPxqcq6Byq0",
    image: "https://upload.wikimedia.org/wikipedia/en/1/1f/Sultan_film_poster.jpg"
  },
  {
    id: 20,
    name: "Shershaah",
    description: "Based on the life of Captain Vikram Batra, a war hero who displayed extraordinary bravery during the Kargil War.",
    duration: "2h 15m",
    releaseDate: "2021-08-12",
    cast: "Sidharth Malhotra,Kiara Advani",
    director: "Vishnuvardhan",
    producer: "Karan Johar",
    rating: 8.4,
    officialUrl: "https://www.youtube.com/watch?v=Q0FTXnefVBA",
    image: "https://upload.wikimedia.org/wikipedia/en/9/91/Shershaah_film_poster.jpg"
  }
];

export default movies;